
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `datasource.url` utilise process.env directement (pas le helper `env()`,
// qui lève une erreur si la variable est absente) : `prisma generate`
// (appelé par postinstall) n'a pas besoin d'une URL valide, et ne doit pas
// échouer si POSTGRES_PRISMA_URL n'est pas encore définie à ce stade du
// build. schema.prisma lit la même variable pour les commandes qui en ont
// réellement besoin (migrate, db seed...).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.POSTGRES_PRISMA_URL ?? "",
  },
});
